-- =============================================================================
-- Halberd & Co — Initial Schema (001)
-- =============================================================================
-- Hand-written initial migration for the Halberd & Co HITL demo domain tables.
-- Field names mirror the Truckstop API data model (camelCase source ->
-- snake_case here) so a future live integration is a connector swap rather than
-- a schema change.
--
-- Applied via Alembic (`alembic upgrade head`). This file is intentionally NOT
-- autogenerated — constraints and field names are explicit.
--
-- The HITL console's own tables (`workflows`, `workflow_items`) plus the Better
-- Auth tables live in the Next.js/Drizzle schema and are NOT created here.
-- =============================================================================

-- Required for gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- updated_at trigger function (shared by every table with an updated_at column)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =============================================================================
-- shippers — Halberd's customers
-- Neon owns the operational layer; HubSpot owns the relationship layer.
-- `hubspot_company_id` is the join key between the two systems.
-- =============================================================================
CREATE TABLE shippers (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- HubSpot join key
    hubspot_company_id  TEXT UNIQUE,                -- HubSpot internal company ID

    -- Minimal identity fields (source of truth is HubSpot — local cache)
    company_name        TEXT NOT NULL,
    doing_business_as   TEXT,
    city                TEXT,
    state_code          CHAR(2),
    zip_code            TEXT,

    -- Operational fields (source of truth is Neon)
    credit_terms_days   INTEGER DEFAULT 30,         -- e.g. Net 30
    status              TEXT NOT NULL DEFAULT 'active'
                            CHECK (status IN ('active', 'inactive', 'prospect')),
    last_load_date      DATE,
    lifetime_load_count INTEGER DEFAULT 0,
    notes               TEXT,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER shippers_set_updated_at
    BEFORE UPDATE ON shippers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================================================
-- carriers — Halberd's carrier network
-- Mirrors Truckstop's NetworkCarrier + carrier profile schemas.
-- =============================================================================
CREATE TABLE carriers (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Identity (mirrors Truckstop NetworkCarrier + carrier profile)
    dot_number              TEXT UNIQUE NOT NULL,
    mc_number               TEXT,
    company_name            TEXT NOT NULL,
    doing_business_as       TEXT,
    carrier_operation       TEXT CHECK (carrier_operation IN ('Interstate', 'IntrastateHmz', 'IntrastateNonHmz')),
    entity_type             TEXT DEFAULT 'Carrier',

    -- Location
    city                    TEXT,
    state_code              CHAR(2),
    postal_code             TEXT,
    country                 CHAR(2) DEFAULT 'US',

    -- Compliance (mirrors Truckstop CarrierHub complianceStatus + FMCSA)
    authority_status        TEXT CHECK (authority_status IN ('active', 'inactive', 'revoked')),
    safety_rating           TEXT CHECK (safety_rating IN ('Satisfactory', 'Conditional', 'Unsatisfactory', 'None')),
    insurance_expiry        DATE,
    compliance_status       TEXT CHECK (compliance_status IN ('Pass', 'Fail', 'Error', 'Warning', 'Pending')),
    last_fmcsa_check_at     TIMESTAMPTZ,

    -- Relationship (mirrors Truckstop isActive + relationship type)
    is_active               BOOLEAN NOT NULL DEFAULT true,
    relationship_type       TEXT DEFAULT 'Watched'
                                CHECK (relationship_type IN ('Favorite', 'Blocked', 'Watched')),
    tier                    TEXT CHECK (tier IN ('preferred', 'backup', 'spot')),
    tender_enabled          BOOLEAN DEFAULT false,  -- Truckstop Book It Now eligibility

    -- Performance (written back by workflows)
    loads_completed         INTEGER DEFAULT 0,
    on_time_rate            NUMERIC(5,2),           -- 0.00–100.00 percent
    claim_count             INTEGER DEFAULT 0,
    invoice_accuracy_rate   NUMERIC(5,2),           -- 0.00–100.00 percent
    last_load_date          DATE,

    -- Financial
    payment_terms_days      INTEGER DEFAULT 30,
    quick_pay_enrolled      BOOLEAN DEFAULT false,
    factoring_company       TEXT,

    -- Preferred lanes
    preferred_lane_notes    TEXT,

    -- Risk (mirrors Truckstop Risk Factor Analysis reportSummary)
    risk_summary            TEXT,
    risk_updated_at         TIMESTAMPTZ,

    -- Internal
    notes                   TEXT,
    added_date              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER carriers_set_updated_at
    BEFORE UPDATE ON carriers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================================================
-- lanes — origin-destination pairs Halberd regularly works
-- The internal rate intelligence layer.
-- =============================================================================
CREATE TABLE lanes (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Origin (mirrors Truckstop Location object)
    origin_city             TEXT NOT NULL,
    origin_state_code       CHAR(2) NOT NULL,
    origin_zip_code         TEXT,
    origin_latitude         NUMERIC(9,6),
    origin_longitude        NUMERIC(9,6),

    -- Destination (mirrors Truckstop Location object)
    destination_city        TEXT NOT NULL,
    destination_state_code  CHAR(2) NOT NULL,
    destination_zip_code    TEXT,
    destination_latitude    NUMERIC(9,6),
    destination_longitude   NUMERIC(9,6),

    -- Equipment (mirrors Truckstop EquipmentCode)
    equipment_code          TEXT NOT NULL DEFAULT 'V'
                                CHECK (equipment_code IN ('V', 'R', 'F', 'SD', 'DD')),
    transportation_mode     TEXT NOT NULL DEFAULT 'TL',

    -- Mileage
    estimated_miles         INTEGER,

    -- Internal rate history (Halberd's own data)
    avg_carrier_rate_per_mile   NUMERIC(6,4),   -- what Halberd pays carriers
    avg_shipper_rate_per_mile   NUMERIC(6,4),   -- what Halberd charges shippers
    avg_margin_percent          NUMERIC(5,2),
    load_count                  INTEGER DEFAULT 0,
    last_load_date              DATE,

    -- Lane pairing / backhaul intelligence
    has_backhaul_pair       BOOLEAN DEFAULT false,
    paired_lane_id          UUID REFERENCES lanes(id),

    -- Metadata
    is_active               BOOLEAN DEFAULT true,
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX lanes_unique_corridor
    ON lanes (origin_state_code, origin_city, destination_state_code, destination_city, equipment_code);

CREATE TRIGGER lanes_set_updated_at
    BEFORE UPDATE ON lanes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================================================
-- loads — the atomic unit of the business
-- Every load connects a shipper, a carrier, and a lane.
-- =============================================================================
CREATE TABLE loads (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Relationships
    shipper_id              UUID NOT NULL REFERENCES shippers(id),
    carrier_id              UUID REFERENCES carriers(id),       -- null until covered
    lane_id                 UUID REFERENCES lanes(id),

    -- Load reference
    load_number             TEXT UNIQUE,                        -- Halberd internal reference

    -- Origin / Destination (denormalized from lane for load-specific addresses)
    origin_address          TEXT,
    origin_city             TEXT NOT NULL,
    origin_state_code       CHAR(2) NOT NULL,
    origin_zip_code         TEXT,
    origin_latitude         NUMERIC(9,6),
    origin_longitude        NUMERIC(9,6),

    destination_address     TEXT,
    destination_city        TEXT NOT NULL,
    destination_state_code  CHAR(2) NOT NULL,
    destination_zip_code    TEXT,
    destination_latitude    NUMERIC(9,6),
    destination_longitude   NUMERIC(9,6),

    -- Equipment (mirrors Truckstop BookedLoad/PostedLoad)
    equipment_code          TEXT NOT NULL DEFAULT 'V',
    equipment_options       TEXT[],                             -- e.g. ['T', 'X'] team, expedited
    transportation_mode     TEXT NOT NULL DEFAULT 'TL',

    -- Freight details (mirrors Truckstop BookedLoad)
    commodity_id            INTEGER,
    commodity_description   TEXT,
    weight_lbs              INTEGER,
    pallet_count            INTEGER,
    mileage                 INTEGER,
    multi_pick_drop         BOOLEAN DEFAULT false,

    -- Dates
    pickup_date             DATE,
    pickup_datetime         TIMESTAMPTZ,
    delivery_date           DATE,
    delivery_datetime       TIMESTAMPTZ,
    actual_pickup_at        TIMESTAMPTZ,
    actual_delivery_at      TIMESTAMPTZ,

    -- Pricing
    shipper_rate            NUMERIC(10,2),                      -- what shipper is charged
    carrier_rate            NUMERIC(10,2),                      -- what carrier is paid
    fuel_surcharge          NUMERIC(10,2),
    fuel_included           BOOLEAN DEFAULT false,
    gross_margin            NUMERIC(10,2) GENERATED ALWAYS AS (shipper_rate - carrier_rate) STORED,
    margin_percent          NUMERIC(5,2),

    -- Status
    status                  TEXT NOT NULL DEFAULT 'pending'
                                CHECK (status IN (
                                    'pending',      -- RFQ received, not yet quoted
                                    'quoted',       -- quote sent to shipper
                                    'won',          -- shipper accepted
                                    'covered',      -- carrier booked
                                    'in_transit',   -- picked up
                                    'delivered',    -- delivered, awaiting docs
                                    'completed',    -- POD received, ready to invoice
                                    'invoiced',     -- shipper invoiced
                                    'paid',         -- shipper paid
                                    'cancelled',    -- cancelled
                                    'lost'          -- shipper went elsewhere
                                )),

    -- Documents
    rate_con_sent_at        TIMESTAMPTZ,
    bol_number              TEXT,
    pod_received_at         TIMESTAMPTZ,

    -- Carrier invoice reconciliation fields
    carrier_invoice_number  TEXT,
    carrier_invoice_amount  NUMERIC(10,2),
    carrier_invoice_status  TEXT CHECK (carrier_invoice_status IN (
                                'pending', 'matched', 'discrepancy', 'approved', 'paid'
                            )),
    invoice_discrepancy_amt NUMERIC(10,2),
    invoice_discrepancy_notes TEXT,

    -- Performance tracking
    on_time_pickup          BOOLEAN,
    on_time_delivery        BOOLEAN,
    had_claim               BOOLEAN DEFAULT false,
    claim_amount            NUMERIC(10,2),

    -- Source / notes
    rfq_source              TEXT CHECK (rfq_source IN ('email', 'form', 'phone', 'api')),
    internal_notes          TEXT,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX loads_shipper_id_idx ON loads (shipper_id);
CREATE INDEX loads_carrier_id_idx ON loads (carrier_id);
CREATE INDEX loads_lane_id_idx ON loads (lane_id);
CREATE INDEX loads_status_idx ON loads (status);
CREATE INDEX loads_pickup_date_idx ON loads (pickup_date);

CREATE TRIGGER loads_set_updated_at
    BEFORE UPDATE ON loads
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- =============================================================================
-- rate_snapshots — market rate data captured at quoting time
-- Mirrors Truckstop Rate Insights API response shape for future live integration.
-- =============================================================================
CREATE TABLE rate_snapshots (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    load_id                 UUID REFERENCES loads(id),
    lane_id                 UUID REFERENCES lanes(id),

    -- Source
    rate_source             TEXT NOT NULL CHECK (rate_source IN ('internal', 'truckstop', 'manual')),
    captured_at             TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Rate data (mirrors Truckstop Rate Insights response)
    rate_type               TEXT CHECK (rate_type IN ('booked', 'posted')),
    low_rate_per_mile       NUMERIC(6,4),
    avg_rate_per_mile       NUMERIC(6,4),
    high_rate_per_mile      NUMERIC(6,4),
    fuel_surcharge_per_mile NUMERIC(6,4),

    -- Context at time of snapshot
    equipment_code          TEXT,
    origin_city             TEXT,
    origin_state_code       CHAR(2),
    destination_city        TEXT,
    destination_state_code  CHAR(2),
    mileage                 INTEGER,

    -- Raw API response (for future debugging/audit)
    raw_response            JSONB
);

-- rate_snapshots has no updated_at column (append-only audit records)
